### ISSUE TITLE
Handle expired tokens

### ISSUE THREAD

**Issue by Hugo-C** [cert-orangecyberdefense/ocd-datalake-rs#10]
As marked in: https://github.com/cert-orangecyberdefense/ocd-datalake-rs/blob/master/src/lib.rs#L38
We have to handle both access token or refresh token that can be expired.

**Comment by Hugo-C** [comment]
@mrtnhwtt do you think we should log when we refresh tokens ? (we don't log anything so far ...)

**Comment by mrtnhwtt** [comment]
I think it's a good idea to log it.
In Datalake hunter we use the following crates for logging
```
log = "0.4.17"
env_logger = "0.9.0"
```
